name: Netlify Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Moving into client app && Install dependencies
        run: cd client && npm install
        
      - name: Moving into client app && Build the React app
        run: cd client && npm run build

      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: deploy --prod
